name: Demo - Nuget Configure Source

on:
  workflow_dispatch:

jobs:
  direct-configure:
    name: Direct configure-source usage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Configure multiple NuGet sources (direct)
        uses: ./nuget/configure-source
        with:
          names: 'DemoSource1, DemoSource2'
          usernames: 'demo-user-1, demo-user-2'
          passwords: 'demo-pass-1, demo-pass-2'
          urls: 'https://example.invalid/feed1/index.json, https://example.invalid/feed2/index.json'

      - name: List configured NuGet sources
        run: dotnet nuget list source

  skips-configure:
    name: Skips configure-source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Configure multiple NuGet sources (direct)
        uses: ./nuget/configure-source
        with:
          usernames: 'demo-user-1, demo-user-2'
          passwords: 'demo-pass-1, demo-pass-2'
          urls: 'https://example.invalid/feed1/index.json, https://example.invalid/feed2/index.json'

      - name: List configured NuGet sources
        run: dotnet nuget list source
